### ISSUE TITLE
How to do prediction and visualize result?

### ISSUE THREAD

**Issue by ghost** [jmercat/KalmanBaseline#1]
Hi,

Kindly help us in providing code for prediction and visualize result

**Comment by jmercat** [comment]
Hi, I should be adding something in the readme file but for now I'll just put that here:
You can visualize predictions by running plot_results and plot global results by running stats_results.
If you want to load your model parameters before plotting:
Pull the small change I've made to correct a path error for loading.
Then, you should put your model file in the trained_models folder.
Finaly, change the load_file_name variable line 70 of plot_results.py to your file name.
You can run plot_results.py.
For stats_results the variable name line 12 should be changed.

This is not clean at all and I'll improve that when the time allows it.

**Comment by ghost** [comment]
Thanks closing the issue
