### ISSUE TITLE
Upload data/TestSet_traj_v2.mat and data/TestSet_tracks_v2.mat

### ISSUE THREAD

**Issue by ghost** [jmercat/KalmanBaseline#2]
Hi,
since US-101-LosAngeles-CA.zip and I-80-Emeryville-CA.zip has been changed in website. 

us101_1 = 'raw/us101-0750-0805.txt';
us101_2 = 'raw/us101-0805-0820.txt';
us101_3 = 'raw/us101-0820-0835.txt';
i80_1 = 'raw/i80-1600-1615.txt';
i80_2 = 'raw/i80-1700-1715.txt';
i80_3 = 'raw/i80-1715-1730.txt';

The above datsaets ha not been available in current website with a change of features in current one.
Can you please upload the data along with TestSet_traj_v2.mat and TestSet_tracks_v2.mat.
Please do the needful

**Comment by jmercat** [comment]
Hi,
Here are the test .mat files:
[Tracks](https://drive.google.com/open?id=171YZvK2DnJbtIgve6qAOkk6AFNrGAYTJ)
[Traj](https://drive.google.com/open?id=1N080iiQc43MTvLMqaLtsZh49okJL0hPx)
For training and validation datasets you will need to run the matlab pre-processing script to generate those files from the NGSIM dataset.

**Comment by ghost** [comment]
Thanks jmercat for sharing mat files. I will cross verify wih the ne wdata in NGSIM dataset .

**Comment by ghost** [comment]
Got all the datasets as per readme section. Closing the issue
