### ISSUE TITLE
Code for  Multi-Modal  Simultaneous  Forecastingof  Vehicle  Position  Sequences  using  Social  Attention

### ISSUE THREAD

**Issue by ghost** [jmercat/KalmanBaseline#3]
Jmercat,

Thanks for publishing the clean code which is good enough to match with paper "Inertial  Single  Vehicle  Trajectory  Prediction  Baselinesand  Applications  with  the  NGSIM  Dataset" and code.

I would ike to know when you are planning to release the code for "Multi-Modal  Simultaneous  Forecastingof  Vehicle  Position  Sequences  using  Social  Attention"

Awaiting for your code again

**Comment by jmercat** [comment]
Hi Sankhanrsss,

Thank you for your interest in my work. I am not planning to release the code for this second article yet. This is an ongoing work that will not be finalized in the near future.

**Comment by ghost** [comment]
thnaks
